[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_poc = "F34cPavCtpxoH3xfvXWw3nRYrK12X8U9Vb5kcAcAVJDK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/darren/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
